### ISSUE TITLE
MBESS change breaks scaleStructure

### ISSUE THREAD

**Issue by rubenarslan** [Matherion/userfriendlyscience#13]
I'm not sure why MBESS revdep checks didn't catch this and why it's flagged in the codebook package tests but not userfriendlyscience, but it seems to boil down to this problem that also occurs in the example of scaleStructure.

```r
exampleData <- testRetestSimData[2:6];

ordinalExampleData <- data.frame(apply(exampleData, 2, cut,
                                        breaks=5, ordered_result=TRUE,
                                        labels=as.character(1:5)));
#' 
 scaleStructure(ordinalExampleData, ci=T);
```

> Error in ci.reliability(S = res$intermediate$polychor, N = res$input$n.observations,  : 
  Both data and covariance matrix cannot be specified simultaneously.

**Comment by rubenarslan** [comment]
Ah, it's a straight-up error in MBESS.

**Comment by yelleKneK** [comment]
Fixed. Version 4.5.1 (uploaded to CRAN) solves this issue.
