### ISSUE TITLE
Error: Package or namespace load failed

### ISSUE THREAD

**Issue by koliphan** [Matherion/userfriendlyscience#6]
Good day,

I tried installing and loading your package today, and received this error message:

>install.packages('userfriendlyscience')
>library(userfriendlyscience)
Error: Package or namespace load failed for 'userfriendlyscience':
object 'cividis' is not exported by 'namespace:viridisLite'

Please let me know if and when a fix will be available. 

Thank you,

Kaitlyn

**Comment by Matherion** [comment]
This is very odd, because 'cividis' does not occur in 'userfriendlyscience' (I did a search in all files in the package). I expect you perhaps have a corrupted version of another package. You could use 'update.packages' to update all your packages, that might fix it?

**Comment by koliphan** [comment]
Hi Matherion,

Yep, that did trick; my bad! Very odd though, as I have been installing packages both prior and since I have attempted to install yours, even within the same R session, and only yours had this issue. You're right that it must have been a problem with one of the package's dependencies then. 

Glad it was a quick fix - thanks for your rapid response. 

Cheers

Kaitlyn

**Comment by Matherion** [comment]
That *does* sounds very weird. but glad this was fixed! 😄
